# Theme version
version: 1.2.0

# Header
menu:
  ##- page: home
  ##  directory: .
  ##  icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - search
  ##- category
  - tag
  - archive
  - recent_posts
  ##- recent_comments
  ##- weibo
  - links
  - notice

# Static files
js: js
css: css

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
##  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml
##baidusitemap:
##  path: baidusitemap.xml

#Archive widgit
archive_type: monthly
archive_date_format: YYYY年M月

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293

#Cmments
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username

# About page 
about:
  photo_url: ## Your photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  email: ## Your email e.g.  zhenggchaoo@gmail.com
  weibo_url: ## Your weibo's url e.g.  http://weibo.com/zhengchaooo
  weibo_name: ## Your weibo's name e.g.  秋过冬漫长
  github_url: ## Your github'url e.g.  https://github.com/chaooo
  github_name: ## Your github'name e.g.  chaooo

# Friend link
links:
  - title: FINAL FANTASY XIV 公式
    url: http://finalfantasyxiv.com
  - title: my Lodestone
    url: http://jp.finalfantasyxiv.com/lodestone/character/1662597/
  - title: my GitHub
    url: https://github.com/quercus2011

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
